version: '3.7'

services:
    catalog:
        container_name: catalog
        build: ./default_api_loopi
        environment:
            CHOKIDAR_USEPOLLING: "true"
        volumes:
            - ./workspace/api/catalog:/var/www/default
            - ./workspace/dev-gcloud.json:/var/www/dev-gcloud.json
        ports:
            - "8080:8080"
    discount:
        container_name: discount
        build: ./default_api_loopi
        environment:
            CHOKIDAR_USEPOLLING: "true"
        volumes:
            - ./workspace/api/discount:/var/www/default
            - ./workspace/dev-gcloud.json:/var/www/dev-gcloud.json
        ports:
            - "8081:8080"
    order:
        container_name: order
        build: ./default_api_loopi
        environment:
            CHOKIDAR_USEPOLLING: "true"
        volumes:
            - ./workspace/api/order:/var/www/default
            - ./workspace/dev-gcloud.json:/var/www/dev-gcloud.json
        ports:
            - "8082:8082"
    provider:
        container_name: provider
        build: ./default_api_loopi
        environment:
            CHOKIDAR_USEPOLLING: "true"
        volumes:
            - ./workspace/api/provider:/var/www/default
            - ./workspace/dev-gcloud.json:/var/www/dev-gcloud.json
        ports:
            - "8083:8083"
    notification:
        container_name: notification
        build: ./default_api_loopi
        environment:
            CHOKIDAR_USEPOLLING: "true"
        volumes:
            - ./workspace/api/notification:/var/www/default
            - ./workspace/dev-gcloud.json:/var/www/dev-gcloud.json
        ports:
            - "8084:8084"
    cart:
        container_name: cart
        build: ./default_api_loopi
        environment:
            CHOKIDAR_USEPOLLING: "true"
        volumes:
            - ./workspace/api/cart:/var/www/default
            - ./workspace/dev-gcloud.json:/var/www/dev-gcloud.json
        ports:
            - "8085:8085"
    redis:
        container_name: redis
        image: redis
        ports:
            - "6379:6379"
